// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID (-1905494168)
#define BOOKERLY_14_FONT_ID (1233852315)
#define BOOKERLY_16_FONT_ID (1588566790)
#define BOOKERLY_18_FONT_ID (681638548)
#define NOTOSANS_12_FONT_ID (-1559651934)
#define NOTOSANS_14_FONT_ID (-1014561631)
#define NOTOSANS_16_FONT_ID (-1422711852)
#define NOTOSANS_18_FONT_ID (1237754772)
#define OPENDYSLEXIC_8_FONT_ID (1331369208)
#define OPENDYSLEXIC_10_FONT_ID (-1374689004)
#define OPENDYSLEXIC_12_FONT_ID (-795539541)
#define OPENDYSLEXIC_14_FONT_ID (-1676627620)
#define UI_10_FONT_ID (-1246724383)
#define UI_12_FONT_ID (-359249323)
#define SMALL_FONT_ID (1073217904)

// SD-cached custom font IDs (one per font-size slot)
#define CUSTOM_SD_FONT_SMALL_ID (-2000000001)
#define CUSTOM_SD_FONT_MEDIUM_ID (-2000000002)
#define CUSTOM_SD_FONT_LARGE_ID (-2000000003)
#define CUSTOM_SD_FONT_XL_ID (-2000000004)
// Deprecated: kept for reference, no longer inserted into the renderer
#define CUSTOM_PSRAM_FONT_ID (-2000000000)
